<?php
/**
 * Created by PhpStorm.
 * User: sonbv
 * Date: 3/2/18
 * Time: 10:27 PM
 */
class TDK_DropShip_Model_Rewrite_Sales_Quote_Address
    extends Mage_Sales_Model_Quote_Address
{
    public function requestShippingRates(Mage_Sales_Model_Quote_Item_Abstract $item = null)
    {
        if (!isset($item)) {
            Mage::helper('tdk_dropship/quote_supplier')->addSupplierIdToQuote($this);
        }
        return parent::requestShippingRates($item); // TODO: Change the autogenerated stub
    }


}