<?php
/**
 * MageWorx
 * Customer Location Extension
 *
 * @category   MageWorx
 * @package    MageWorx_CustomerLocation
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<?php if ($_item = $this->getItem()): ?>
<?php $_geoip = $_item->getGeoIp() ?>
<?php if ($_item->getIp()): ?>
    <?php echo $_item->getIp() ?>
    <?php endif; ?>
<?php if ($_geoip->getCode()): ?>
    <?php if ($_geoip->getFlag()): ?>
        <img class="v-middle" src="<?php echo $_geoip->getFlag() ?>" title="<?php echo $_geoip->getCode() ?>" />
        <?php endif; ?>
    <?php echo $_geoip->getCode() ?>, <?php echo $_geoip->getCountry() ?><?php if (Mage::helper('mageworx_geoip')->isCityDbType()): ?>,
        <?php echo implode(', ', array_filter(array($_geoip->getRegion(), $_geoip->getCity(), $_geoip->getPostalCode()))) ?>
        <?php endif; ?>
    <?php else: ?>
    <?php echo $this->__('n/a') ?>
    <?php endif; ?>
<?php endif; ?>