<div class="full pdgTop15">
				<div class="col98">
					<div class="heading-bar">
						<div class="bar">
							<span class="title">Our Brands</span>
						</div>
					</div>
					
					<ul class="logos">
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/logo1.jpg" alt="" /></li>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/logo2.jpg" alt="" /></li>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/logo3.jpg" alt="" /></li>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/logo4.jpg" alt="" /></li>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/logo5.jpg" alt="" /></li>
						
						
					</ul>
				</div>
			</div>