<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php
/**
 * - Added grid classes for cross-sell items
 * - Image size changed from 75 to 65
 */
//echo $this->getItemCount();
 ?>
<?php if($this->getItemCount()): ?>
<script src="http://bxslider.com/lib/jquery.bxslider.js"></script>
<script> 
	jQuery(document).ready(function(){
	  jQuery('#crosssell-products-list').bxSlider({
		auto: true,
		speed:4000,
		pause:10000,
		minSlides: 1,
		maxSlides: 6,
		moveSlides:6,
		slideWidth: 175,
		slideMargin: 10
	  });
	});    
</script>
<style>
	.bx-wrapper{
		margin-bottom:0 !important;
	}
	.bx-controls{
		position: absolute !important;
		top: 20px!important;
		right: 36px !important;
	}
	.bx-controls-direction{
		display: inline-block;
		width: 70px;
		height: 0;
		top: -20px;
		position: absolute;
		right: -38px;
	}
	.bx-viewport{
		height:auto !important
	}
</style>
<div class="full">
	<div class="col98" style="padding-bottom:0px;">
	<div class="heading-bar" style="z-index:999">
		<div class="bar">
			<span class="title"><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></span>
		</div>
	</div>
	<ul id="crosssell-products-list" class="store-list">
		
		<?php 
		
		foreach ($this->getItems() as $_item): 
		?>
			<li class="" style="padding:0px;">
				<div class="seller-box-store">
					<a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
						<img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail'); ?>"  alt="<?php echo $this->escapeHtml($_item->getName()) ?>" class="ct" />
					</a>
					<div class="seller-box-list">
						<ul>
							<li>
								<a href="<?php echo $this->getAddToWishlistUrl($_item) ;?>">
									<img alt="" src="<?php echo $this->getSkinUrl();?>images/heart.jpg">
								</a>
							</li>
							<li>
								<a href="<?php echo $this->getAddToCompareUrl($_item) ;?>">
									<img alt="" src="<?php echo $this->getSkinUrl();?>images/db.jpg">
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="product-details">
					<div class="open-sans-bold-headings-14">
						<a href="<?php echo $_item->getProductUrl() ?>">
							<?php echo substr($this->escapeHtml($_item->getName()),0, 20).'....'?>
							<?php //echo $this->escapeHtml($_item->getName()) ?>
						</a>
					</div>
					<div class="open-sans-bold-headings-18">
						<?php echo $this->getPriceHtml($_item, true) ?>
					</div>
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				</div>
			</li>
		<?php endforeach; ?>
	</ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>   </div>
</div>
<?php endif; ?>
