<?php

/**
 * Created by PhpStorm.
 * User: sonbv
 * Date: 2/16/18
 * Time: 8:28 PM
 */
class TDK_DropShip_Model_Supplier extends Mage_Core_Model_Abstract
{
    protected $_adminUser;

    protected $_roleId;

    public function getName()
    {
        return
            $this->getData('first_name') .
            ' ' .
            $this->getData('last_name');
    }

    protected function _construct()
    {
        $this->_init('tdk_dropship/supplier');
    }

    protected function _beforeSave()
    {
        $this->getAdminUser()
            ->addData(array(
                'firstname' => $this->getFirstName(),
                'lastname' => $this->getLastName(),
                'username' => $this->getUsername(),
                'email' => $this->getEmail(),
                'new_password' => $this->getNewPassword(),
            ));

        $this->getAdminUser()->save();
        if ($this->getAdminUser()->isObjectNew()) {
            if (!$this->getRoleId()) {
                Mage::throwException('Please create new Role with name Suppliers');
            }
            $this->getAdminUser()->setRoleIds(array($this->getRoleId()))
                ->setRoleUserId($this->getAdminUser()->getUserId())
                ->saveRelations();

            $this->setAdminUserId($this->getAdminUser()->getId());
        }

        // street address
        $this->setData('street_address', Mage::helper('core')->jsonEncode((array) $this->getData('street_address')));

        return parent::_beforeSave();
    }

    protected function _afterLoad()
    {
        $adminUser = $this->getAdminUser();
        $this->addData(array(
            'username' => $adminUser->getUsername()
        ));
        $this->setData('street_address', (array) Mage::helper('core')->jsonDecode($this->getData('street_address')));

        return parent::_afterLoad(); // TODO: Change the autogenerated stub
    }

    protected function _beforeDelete()
    {
        if ($this->getAdminUser()->getId()) {
            $this->getAdminUser()->delete();
        }
        return parent::_beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Mage_Admin_Model_User
     */
    public function getAdminUser()
    {
        if (!isset($this->_adminUser)) {
            $adminId = (int)$this->getAdminUserId();
            $this->_adminUser = Mage::getModel('admin/user');
            if ($adminId) {
                $this->_adminUser->load($adminId);
            }
        }
        return $this->_adminUser;
    }

    protected function getRoleId()
    {
        if (!isset($this->_roleId)) {
            // instance of the admin_role
            $model = Mage::getModel('admin/role');

            $role = $model->getCollection()
                ->addFieldToFilter('role_name', ['eq' => 'Suppliers'])
                ->getFirstItem();
            if ($role->getId()) {
                $this->_roleId = $role->getId();
            } else {
                $this->_roleId = false;
            }
        }
        return $this->_roleId;
    }

    /**
     * @param $productId
     * @return bool
     */
    public function addProductById($productId)
    {
        if ($productId > 0) {
            Mage::getModel('tdk_dropship/supplierProduct')
                ->setProductId($productId)
                ->setSupplierId($this->getId())
                ->save();
        }
        return false;
    }

    public function getFullName()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

}