<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 10/21/15
 * Time: 4:22 PM
 */
?>
<?php /* @var $this SM_XReport_Block_Adminhtml_Store_Switcher */ ?>
<?php if ($websites = $this->getWebsites()): ?>
<p class="switcher"><label for="store_switcher"><?php echo $this->__('Choose Store View:') ?></label>
    <select name="store_switcher" id="store_switcher" class="form-control" ng-model="switchStore.currentStore">
        <?php if ($this->hasDefaultOption()): ?>
            <option value=""><?php echo $this->getDefaultStoreName() ?></option>
        <?php endif; ?>
        <?php foreach ($websites as $website): ?>
            <?php $showWebsite = false; ?>
            <?php foreach ($website->getGroups() as $group): ?>
                <?php $showGroup = false; ?>
                <?php foreach ($this->getStores($group) as $store): ?>
                    <?php if ($showWebsite == false): ?>
                        <?php $showWebsite = true; ?>
                        <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                    <?php endif; ?>
                    <?php if ($showGroup == false): ?>
                        <?php $showGroup = true; ?>
                        <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                    <?php endif; ?>
                    <option
                        value="<?php echo $this->escapeHtml($store->getId()) ?>"<?php if ($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>
                        &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                <?php endforeach; ?>
                <?php if ($showGroup): ?>
                    </optgroup>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </select>
    <?php endif; ?>
