<?php
/**
 * Created by PhpStorm.
 * User: sonbv
 * Date: 3/7/18
 * Time: 1:43 AM
 */

require_once(Mage::getModuleDir('controllers','Mage_Adminhtml').DS.'Sales'.DS.'Order'.DS.'ShipmentController.php');

class TDK_DropShip_Admin_SupplierShipmentController extends Mage_Adminhtml_Sales_Order_ShipmentController
{
    public function viewAction()
    {
        parent::viewAction(); // TODO: Change the autogenerated stub
    }

    public function newAction()
    {
        parent::newAction(); // TODO: Change the autogenerated stub
    }

    protected function _isAllowed()
    {
        $action = strtolower($this->getRequest()->getRequestedActionName());
        return in_array($action, array('new', 'view'));
//        return parent::_isAllowed(); // TODO: Change the autogenerated stub
    }

    public function getFullActionName($delimiter='_')
    {
        return $this->getRequest()->getRequestedRouteName().$delimiter.
            'sales_order_shipment'.$delimiter.
            $this->getRequest()->getRequestedActionName();
    }


}