<?php

$_order = $this->getOrder();
$_source = $this->getSource();

$discount = Mage::getModel('adminhtml/session')->getData('xpos_creditmemo_discount');
if (!is_null($discount)) {
    ?>
    <tr>
        <td <?php echo $this->getLabelProperties() ?>>
            <?php echo Mage::helper('xpos')->__('Xpos discount'); ?>
        </td>
        <td <?php echo $this->getValueProperties() ?>><?php echo $discount ?></td>
    </tr>
<?php };
?>
