<?php

/**

 * Featured Products Slider

 */

?>

<?php

    $_productCollection=$this->getLoadedProductCollection();

    $_collectionSize = $_productCollection->count();
	
	$_helper = $this->helper('catalog/output');

    $theme = $this->helper('ultimo');


    $helpLabels = $this->helper('ultimo/labels');


    $helpTemplate = $this->helper('ultimo/template');


    $helpImg = $this->helper('infortis/image');


    $sliderClasses = '';


    $gridClasses = '';
	
	$sliderId = "itemsliderbesty";
    
    //Slider parameters
    //--------------------------------------------------------------

    //Responsive mode on/off
    $isResponsive = $this->getIsResponsive(); //param: is_responsive
    if ($isResponsive === NULL) //Param not set
    {
        $isResponsive = true; //IMPORTANT: enabled by default
    }

    //Assign number of items in a row to specific viewport width
    $breakpoints = $this->getBreakpoints(); //param: breakpoints
    if ($breakpoints === NULL) //Param not set
    {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 5], [1280, 6]'; //Set default breakpoints
    }

    //Number of items in a row displayed if responsive mode is off
    $showItems = $this->getShowItems(); //param: show_items
    if (!$showItems) //Param not set or equals zero
    {
        $showItems = 3; //Set default number of items
    }

    //Pagination on/off
    $pagination = $this->getPagination(); //param: pagination

    //Slider initial delay
    $initDelay = 0;
    $initDelay = intval($this->getInitDelay()); //param: init_delay

    //Image width
    $imgWidth = $this->getImgWidth(); //param: img_width
    if ($imgWidth === NULL) //Param not set
    {
        $imgWidth = 196; //Set default value
    }
    else
    {
        $imgWidth = intval($imgWidth);
    }

        //Image aspect ratio
        if ($theme->getCfg('category/aspect_ratio'))
        {
            $imgHeight = 0; //Keep aspect ratio - height will be calculated automatically based on width
        }
        else
        {
            $imgHeight = $imgWidth; //Don't keep aspect ratio - height is the same as width
        }

    //Image height
    if ($this->getImgHeight() !== NULL) //param: img_height
    {
        //If param is set, it overrides default height and aspect ratio settings
        $imgHeight = intval($this->getImgHeight());
    }
    
    //Slider timeout. Set to enable automatic scrolling.
    $timeout = $this->getTimeout(); //param: timeout
    if ($timeout === NULL) //Param not set
    {
        $timeout = intval($theme->getCfg('product_slider/timeout'));
    }
    else
    {
        $timeout = intval($timeout);
    }

    //Number of items that should move on scrolling
    $move = $this->getMove(); //param: move
    if ($move === NULL) //Param not set
    {
        $move = 0; //By default scroll all visible items
    }
    else
    {
        $move = intval($move);
    }

    //If set, slider will loop.
    $loop = $this->getLoop(); //param: loop
    if ($loop === NULL) //Param not set
    {
        $loop = $theme->getCfg('product_slider/loop');
    }

    //Speed (arrows / touch swipe)
    $speed = intval($theme->getCfg('product_slider/speed'));

    //Speed (automatic scrolling / pagination)
    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

    //Pause slider on mouse hover
    $pause = $theme->getCfg('product_slider/pause');

    //Lazy loading
    $lazy = $theme->getCfg('product_slider/lazy');

    //Slider classes
    //--------------------------------------------------------------
    if($isResponsive)
    {
        $sliderClasses .= ' itemslider-responsive';
    }

    if ($_collectionSize == 1)
    {
        $sliderClasses .= ' single-item';
    }

    //Product grid classes
    //--------------------------------------------------------------
    //Size of grid elements
    $size = $this->getSize(); //param: size
    if ($size)
    {
        $gridClasses = ' ' . $size;
    }
    else
    {
        if ($showItems >= 8)
        {
            $gridClasses = ' size-xs';
        }
        elseif ($showItems >= 3)
        {
            $gridClasses = ' size-s';
        }
    }

    //Align elements to the center
    if ($this->getCentered()) //param: centered
    {
        $gridClasses .= ' centered';
    }

    //Set equal height for all items
    if ($this->getEqualHeight()) //param: equal_height
    {
        $gridClasses .= ' equal-height';
    }

?>
<div class="full">
<?php //if ($_productCollection && ($_collectionSize = $this->getCollectionCount())): ?>

<div class="col75">
                    <div class="heading-bar">
                        <div class="bar">
                            <span class="title">Best sellers</span>
                            <span class="viewall"><a href="<?php echo $this->getUrl(); ?>best-seller.html">View All</a></span>
                        </div>
                    </div>
                    
					<div class="itemslider-wrapper itemslider-new-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
    <div id="<?php echo $sliderId; ?>" class="sss itemslider<?php if($sliderClasses) echo $sliderClasses; ?> products-grid<?php if($gridClasses) echo $gridClasses; ?>">
					
					<?php foreach ($_productCollection as $_product): ?>
					
                    <div class="item" style="250px;">
                        <div class="full">
                            <div class="seller-box">
                               <a  href="<?php echo $_product->getProductUrl() ?>" >
							   
							   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"class="ct" />
							   
							   <?php echo $helpLabels->getLabels($_product); //Product labels ?>
							   
                               </a>
                                
                                <div class="seller-box-list">
                                    <ul>
                                        <li><a href="<?php echo $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;"><img src="<?php echo $this->getskinUrl();?>images/heart.jpg" alt=""  title="Add To Wishlist"/></a></li>
                                        <li><a href="<?php echo  $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);?>"><img src="<?php echo $this->getskinUrl();?>images/db.jpg" alt=""  title="Add To Compare"/></a></li>
                                        <li><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><img src="<?php echo $this->getskinUrl();?>images/share.jpg" alt=""  title="Share This"/></a></li>
                                    </ul>
                                </div>
                            </div>
                            <span class="open-sans-bold-14"><a href="javascript:void(0);"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></span>
                            
                            <div class="full pdgTop10">
                                <div class="alignleft">
                          <?php $this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper'); ?>
						  <?php  echo $this->_reviewsHelperBlock->getSummaryHtml($_product, false, false); ?>
			                </div>
                                
                                <div class="alignright"><span class="open-sans-bold-18"><?php echo $this->getPriceHtml($_product, true) ?></span></div>
                            </div>
                            
                             <?php 							 ?>
                            <div class="alignleft">
                            <?php if($_product->isSaleable()): ?>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
<?php else: ?>
    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>



                            </div>
                        </div>
                    </div>
                <?php endforeach;?>
                    </div>
                    </div>
                    </div>
<?php // endif; ?>
<div class="col22">
                    <div class="img">
                        <a href="../index.php/special.html">
                         <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('best-seller-banner-image')->toHtml(); ?> 
                        </a>
                    </div>
                </div>

</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(function($) {
        
        var owl = $('#<?php echo $sliderId; ?>');
        owl.owlCarousel({

        <?php if ($lazy): ?>
            lazyLoad: true,
        <?php endif; ?>

        <?php if(!$isResponsive): ?>
            responsive: false,
            items: <?php echo $showItems; ?>,
        <?php else: ?>
            itemsCustom: [ <?php echo $breakpoints; ?> ],
            responsiveRefreshRate: 50,
        <?php endif; ?>

        <?php if ($speed): ?>
            slideSpeed: <?php echo $speed; ?>,
        <?php endif; ?>

        <?php if ($autoSpeed): ?>
            paginationSpeed: <?php echo $autoSpeed; ?>,
        <?php endif; ?>

        <?php if ($move !== 1): ?>
            scrollPerPage: true,
        <?php endif; ?>

        <?php if ($timeout): ?>
            autoPlay: <?php echo $timeout; ?>,
        <?php endif; ?>

        <?php if ($pause): ?>
            stopOnHover: true,
        <?php endif; ?>

        <?php if ($loop): ?>
            rewindNav: true,
            rewindSpeed: 600,
        <?php else: ?>
            rewindNav: false,
        <?php endif; ?>

        <?php if ($pagination): ?>
            pagination: true,
        <?php else: ?>
            pagination: false,
        <?php endif; ?>

            navigation: true,
            navigationText: false

        }); //end: owl

    });
//]]>
</script>
<style>
.owl-item{
	width:250px !important;
}
.sss .owl-buttons{
	top:-20px !important;
}
</style>