<?php

    /**
     * Created by PhpStorm.
     * User: vjcspy
     * Date: 6/16/15
     * Time: 6:02 PM
     */
    class SM_XPayment_Model_MultiplePaymentMethod extends Mage_Payment_Model_Method_Abstract
    {
        protected $_code           = 'xpaymentMultiple';
        protected $_canUseInternal = true;
        protected $_canUseCheckout = false;
        protected $_infoBlockType  = 'xpayment/info_xpaymentMultiple';
        protected $_formBlockType  = 'xpayment/form_xpaymentMultiple';
        //protected $_canUseForMultishipping = false;
        //protected $_isGateway = true;
        //protected $_canAuthorize = true;

        protected function _construct()
        {
            parent::_construct(); // TODO: Change the autogenerated stub
        }

        public function authorize(Varien_Object $payment, $amount)
        {
            Mage::log("Dummypayment\tIn authorize");

            return $this;
        }
//        public function getQuoteId() {
//                return Mage::getSingleton('checkout/session')->getQuoteId();
//        }
        public function assignData($data)
        {
            parent::assignData($data); // TODO: Change the autogenerated stub
            if (!($data instanceof Varien_Object)) {
                $data = new Varien_Object($data);
            }
            $data = $data->getData();

            $dataSplit = array();
            $dataModel = array();

//            $currentQuoteId = $this->getQuoteId();
//            $dataSplit['check_no'] = $currentQuoteId;
            foreach ($data as $k => $v) {
                if ($v != 0 && $k != 'enable') {
                    $dataSplit[$k] = $v;
                    $currentData = array(
//                        'check_no' => $currentQuoteId,
                        'code'     => $k,
                        'amount'   => $v,
                    );
                    $dataModel[] = $currentData;
                }
            }
            foreach ($dataModel as $k => $v) {
                $model = Mage::getModel("xpayment/xpayment");
                $model->addData($v);
                    $model->save();
            }
//        $checkNo = $data->getCheckNo();
//        $xposCashAmount = $data->getXposCash();
//        $xposCcAmount = $data->getXposCc();
//        $dataAddition=array(
//            'checkNo' => $checkNo,
//            'xposcash' => $xposCashAmount,
//            'xposcc' => $xposCcAmount,
//        );
            $this->getInfoInstance()->setAdditionalData(serialize($dataSplit));

            return $this;
        }


        public function validate()
        {
            return parent::validate(); // TODO: Change the autogenerated stub
        }

        public function isApplicableToQuote($quote, $checksBitMask)
        {
            return parent::isApplicableToQuote($quote, $checksBitMask); // TODO: Change the autogenerated stub
        }


    }
