<?php
/**
 * Created by PhpStorm.
 * User: sonbv
 * Date: 2/19/18
 * Time: 6:02 AM
 */
class TDK_DropShip_Block_Adminhtml_Catalog_Product_Tab_Supplier
    extends Mage_Adminhtml_Block_Widget_Grid
    implements Mage_Adminhtml_Block_Widget_Tab_Interface
{

    public function __construct()
    {
        parent::__construct();

        $this->setId('supplierProduct');
        $this->setDefaultSort('supplier_id');
        $this->setDefaultSort('DESC');
        $this->setUseAjax(true);
        $this->setFilterVisibility(false);
        $this->setEmptyText(Mage::helper('tdk_dropship')->__('There are no suppliers for this product'));
    }

    protected function _prepareCollection()
    {

        $collection = Mage::getResourceModel('tdk_dropship/supplier_collection');
        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $this->addColumn('first_name', array(
            'header' => Mage::helper('tdk_dropship')->__('First Name'),
            'index' => 'first_name',
        ));

        $this->addColumn('last_name', array(
            'header' => Mage::helper('tdk_dropship')->__('Last Name'),
            'index' => 'last_name',
        ));

        $this->addColumn('email', array(
            'header' => Mage::helper('tdk_dropship')->__('Email'),
            'index' => 'email',
        ));


        return parent::_prepareColumns();
    }

    protected function _prepareMassaction()
    {
        $this->setMassactionIdField('supplier_id');
        $this->getMassactionBlock()->setUseAjax(true);
        $this->getMassactionBlock()->setFormFieldName('product_supplier');

        $this->getMassactionBlock()->addItem('Save', array(
            'label'=> Mage::helper('tdk_dropship')->__('Save'),
            'url'  => $this->getUrl('*/product_supplier/save', array(
                'product_id' => $this->_getProductId(),
            )),
            'complete' => 'alert("Save success");',
        ));

        return parent::_prepareMassaction();
    }

    protected function _prepareMassactionColumn()
    {
        /* Hack checked massaction checkbox */
        $collection = Mage::getResourceModel('tdk_dropship/supplierProduct_collection');
        $collection->addFieldToFilter('product_id', $this->_getProductId());
        $supplierIds = array();
        foreach ($collection as $supplier) {
            $supplierIds[] = $supplier->getSupplierId();
        }
        $this->getRequest()
            ->setParam($this->getMassactionBlock()->getFormFieldNameInternal(), implode($supplierIds, ','));
        return parent::_prepareMassactionColumn();
    }

    public function getGridUrl()
    {
        $productId = $this->_getProductId();
        return $this->getUrl('*/product_supplier/grid', array(
            'id' => $productId,
        ));
    }

    public function getTabUrl()
    {
        return $this->getGridUrl();
    }

    public function _toHtml()
    {
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }

    /**
     * Return Tab label
     *
     * @return string
     */
    public function getTabLabel()
    {
        return 'Suppliers';
    }

    /**
     * Return Tab title
     *
     * @return string
     */
    public function getTabTitle()
    {
        return 'Suppliers';
    }

    /**
     * Can show tab in tabs
     *
     * @return boolean
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Tab is hidden
     *
     * @return boolean
     */
    public function isHidden()
    {
        return false;
    }

    public function getTabClass()
    {
        return 'ajax';
    }

    /**
     * @return mixed
     * @throws Exception
     */
    protected function _getProductId()
    {
        $productId = $this->getRequest()->getParam('id');
        return $productId;
    }
}